# import os

API_KEY = '1889907691:AAG-0t402JCpta3qtqB-hdRwKzdikg1N1_s'
LETS_PLAY_GAME = 'Lets Play a Game!'
WELCOME_MESSAGE = 'Welcome to The Race Against TIME!'
GAME_HAXBALL = 'HAXBALL'
GAME_UNO = 'UNO'
GAME_SKRIBBL = 'SKRIBBLE.IO'
GAME_GARTIC = 'GARTIC PHONE'
GAME_CODENAMES = 'CODENAMES'
GAME_SPYFALL = 'SPYFALL'
GAME_FAMILY = 'FAMILY STYLE'
GAME_SCATTER = 'SCATTERGORIES'
GAME_SECRET = 'SECRET HITLER'
GAME_AGAR = 'AGAR.IO'
GAME_HIDE = 'HIDE ONLINE'
GAME_SMASHKARTS = 'SMASHKARTS.IO'
GAME_JEOPARDY = 'JEOPARDY'
GAME_WELP = 'WELP'
LIST_ALL_GAMES = 'Go back to list of games'

def get_game_names():
  return [GAME_HAXBALL,
          GAME_UNO,
          GAME_SKRIBBL,
          GAME_GARTIC,
          GAME_CODENAMES,
          GAME_SPYFALL,
          GAME_FAMILY,
          GAME_SCATTER,
          GAME_SECRET,
          GAME_AGAR,
          GAME_HIDE,
          GAME_SMASHKARTS,
          GAME_JEOPARDY,
          GAME_WELP]
          